name: 'Main Action'
description: 'Composite action that calls Step A and Step B'
runs:
  using: "composite"
  steps:
    - name: Run Step A
      uses: ./.github/actions/step_a.action.yml
    
    - name: Run Step B
      uses: ./.github/actions/step_b.action.yml
