name: 'Main Action'
description: 'Composite action that calls Step A and Step B'
runs:
  using: "composite"
  steps:
    - name: Run Step A
      uses: srizzo/workflow-pocs/step_a@main

    - name: Run Step B
      uses: srizzo/workflow-pocs/step_b@main
