name: After Manual Workflow

on:
  workflow_run:
    workflows: ["Manual Workflow"]
    types:
      - completed

jobs:
  after-manual-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check Manual Print Commit workflow status
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "The Manual Print Commit workflow completed successfully!"
            echo "It was triggered by a ${{ github.event.workflow_run.event }} event."
            echo "The run id was ${{ github.event.workflow_run.id }}."
          else
            echo "The Manual Print Commit workflow did not complete successfully."
            echo "Its status was: ${{ github.event.workflow_run.conclusion }}"
          fi
