name: deploy to lambda
on:
  release:
    types: [ published ]
  workflow_run:
    workflows: [ "Create Tag and Pre-Release" ]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  deploy_to_lambda:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      
      - name: Install dependencies
        run: |
          bundle install --path vendor/bundle
      
      - name: Create deployment package
        run: |
          zip -r deployment.zip . -x .git/\* -x .github/\* -x tmp/\*
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name ruby-lambda-function --zip-file fileb://deployment.zip
          aws lambda update-function-configuration --function-name ruby-lambda-function \
            --handler lambda_function.handler \
            --runtime ruby3.2 \
            --timeout 10 \
            --memory-size 128
