name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash to print'
        required: true
        type: string


jobs:
  manual-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print Commit Hash
        run: echo "The provided commit hash is ${{ github.event.inputs.commit_hash }}"

