name: Process Release

on:
  release:
#    types: [published]

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print Release Message
        run: |
          echo "A new release has been published!"
          echo "Release Tag: ${{ github.event.release.tag_name }}"
          echo "Release Name: ${{ github.event.release.name }}"
