name: Publish Draft Release

on:
  release:
    types: [created]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    if: github.event.release.draft == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit ${{ github.event.release.tag_name }} --draft=false
