name: Create Tag and Pre-Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME=$(date +'%Y.%m.%d-%H%M%S')
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Pre-Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.create_tag.outputs.tag_name }} \
            --prerelease \
            --title "Pre-Release ${{ steps.create_tag.outputs.tag_name }}" \
            --notes "Pre-release created automatically."
