name: Trigger Workflow on Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development

jobs:
  trigger_workflow_on_environment:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
      url: ${{ format('https://example.com/preview/{0}', github.event.pull_request.number) }}

    steps:
      - name: deploy
        run: echo "Running workflow on ${{ github.event.inputs.environment }}"
